package ch.pam_exchange.pam_tc.pamuser.api;

public interface PAMUserMessageConstants {

	String ERR_EXCEPTION= "PAM-EF-1531";
	String ERR_CONNECTION= "PAM-EF-1532";
	String ERR_AUTHENTICATION= "PAM-EF-1533";
	String ERR_AUTHORIZED= "PAM-EF-1534";
	String ERR_STATUSCODE_NOTFOUND= "PAM-EF-1535";
	String ERR_STATUSCODE_INVALID= "PAM-EF-1536";
	String ERR_STATUSCODE_NOT_OK= "PAM-EF-1537";
	String ERR_PASSWORD_INVALID_CHARACTERS= "PAM-EF-1538";
	String ERR_USER_NOT_FOUND= "PAM-EF-1539";
	String ERR_PASSWORD_LENGTH= "PAM-EF-1540";
	String ERR_MASTERACCOUNT_REQUIRED= "PAM-EF-1541";
	String ERR_READ_TIMEOUT= "PAM-EF-1542";
	String ERR_DEVICE_NOT_FOUND= "PAM-EF-1543";
	String ERR_APPLICATION_NOT_FOUND= "PAM-EF-1544";
	String ERR_ACCOUNT_NOT_FOUND= "PAM-EF-1545";
	String ERR_PAM_REMOTE= "PAM-EF-1546";

}
